RL_PANEL_HTML = """<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>合成大西瓜 RL Trial Panel</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#fff;color:#202124;font:13px/1.45 -apple-system,BlinkMacSystemFont,"PingFang SC","Helvetica Neue",sans-serif}header{padding:19px 24px 7px;text-align:center}h1{font-size:20px;font-weight:600;margin:0 0 12px}main{padding:8px 22px 26px;max-width:2000px;margin:auto}.toolbar{display:flex;justify-content:center;gap:8px;align-items:center;flex-wrap:wrap;margin:0 auto 12px;color:#555;font-size:12px}button,input,select{font:inherit;padding:5px 8px;border:1px solid #ccc;border-radius:4px;background:#fff;color:#333}button{cursor:pointer}.summary{text-align:center;color:#777;font-size:11px;margin:0 0 7px}.legend{display:flex;gap:12px;justify-content:center;flex-wrap:wrap;font-size:10px;margin:0 0 5px;color:#555}.legend i{display:inline-block;width:13px;height:3px;vertical-align:middle;margin-right:4px}.charts{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px 14px}.chart{min-width:0;height:300px}.chart canvas{display:block;width:100%;height:270px}.chart h2{text-align:center;font-size:13px;font-weight:600;margin:0 0 2px}.ledger{margin-top:24px;overflow:auto}.ledger h2{text-align:center;font-size:13px;font-weight:600;margin:0 0 9px}.ledger table{width:100%;border-collapse:collapse;font-size:10px;white-space:nowrap}.ledger th,.ledger td{border:1px solid #c8c8c8;text-align:center;padding:3px 5px}.ledger th{background:#333;color:#fff;position:sticky;top:0}.ledger tr.mlp td{background:#eaf2fb}.ledger tr.transformer td{background:#fdeaea}.ledger tr.qwen td{background:#f5ece7}.ledger tr.k200 td{background:#fff3e0}.ledger tr:hover td{filter:brightness(.96)}.ledger input{padding:0}.empty{padding:32px;text-align:center;color:#777;grid-column:1/-1}@media(max-width:1000px){main{padding:8px}.charts{grid-template-columns:repeat(2,minmax(0,1fr))}.chart{height:270px}.chart canvas{height:240px}}@media(max-width:650px){.charts{grid-template-columns:1fr}.chart{height:290px}.chart canvas{height:260px}}
</style>
</head>
<body>
<header>
<h1>合成大西瓜 RL —— 全 trial 总览 panel（架构 / 吞吐 / 上限 / 台账）</h1>
<div class="toolbar"><label>阶段 <select id="wave"><option value="">全部</option></select></label><label>算法 <select id="algorithm"><option value="">全部</option></select></label><label>搜索 <input id="search" type="search" placeholder="trial / host"></label><button id="all">全选当前</button><button id="clear">清空曲线选择</button></div>
<div class="summary" id="summary">载入历史 trial…</div><div class="legend" id="legend"><span><i style="background:#222"></i>实线：训练 online episode score（ε-greedy，近似 episode return）</span><span><i style="background:#222;border-top:1px dashed #222"></i>同色虚线：固定种子 greedy eval</span><span>灰色虚线：online P25/P75 或 P90；online 升而 greedy 平提示 train/eval gap（含 ε 差异）</span></div>
</header>
<main>
<section class="charts" id="charts"><div class="empty">加载试验曲线…</div></section>
<section class="ledger"><h2 id="ledger-title">完整 Trial 台账</h2><table><thead><tr><th>对比</th><th>trial</th><th>arch</th><th>params</th><th>board</th><th>batch</th><th>grad</th><th>env steps</th><th>env/s</th><th>samples/s</th><th>online score</th><th>greedy best</th><th>greedy last</th><th>episodes</th><th>max fruit</th><th>moves</th><th>wave</th><th>host</th></tr></thead><tbody id="body"><tr><td colspan="18">加载中</td></tr></tbody></table></section>
</main>
<script>
const $=selector=>document.querySelector(selector);
const colors={mlp:'#1f77b4',settf:'#d62728',qwen:'#8c564b',other:'#2ca02c'};
const curvePalette=['#1f77b4','#ff7f0e','#d62728','#9467bd','#17becf','#2ca02c','#7f7f7f','#e377c2'];
const preferred=['w3b_mlp_deep','w3b_tf_deep','w3c_tf_xl','w4_k200_cont','w4_k200_scratch','w6_h720_fixed','w6_var','w6_max_fixed','w6_debug','w6_var_xl'];
let rows=[],selected=new Set();
const esc=value=>String(value??'—').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const number=(value,digits=0)=>value==null||!Number.isFinite(Number(value))?'—':Number(value).toLocaleString(undefined,{maximumFractionDigits:digits});
const arch=trial=>trial.config.arch||trial.algorithm;
const color=trial=>colors[arch(trial)]||colors.other;
function filtered(){const wave=$('#wave').value,algorithm=$('#algorithm').value,search=$('#search').value.toLowerCase();return rows.filter(row=>(!wave||row.trial.experiment===wave)&&(!algorithm||arch(row.trial)===algorithm)&&(!search||`${row.trial.name} ${row.trial.experiment} ${row.trial.config.host||''}`.toLowerCase().includes(search)))}
function board(trial){const geometry=trial.config.geometry||{},show=value=>Array.isArray(value)?`${value[0]}–${value[1]}`:value;if(geometry.width||geometry.height)return `${show(geometry.width)||448}×${show(geometry.height)||'?'}`;if(trial.config.killy!=null)return `killy ${trial.config.killy}`;if(trial.name?.startsWith('w4_k200'))return 'killy 200';if(trial.name?.startsWith('w5_k220'))return 'killy 220';return /wave[123]/.test(trial.experiment||'')?'stock':'—'}
function xValues(row,axis){const evaluation=row.evaluation||{},steps=evaluation.env_steps||[];if(axis==='grad')return evaluation.grad_steps||steps.map(()=>null);if(axis==='hours'){const times=evaluation.time||[],start=times.find(value=>value!=null)||0;return times.map(value=>value==null?null:(value-start)/3600)}return steps}
function drawChart(title,series,options={}){
  const element=document.createElement('article');element.className='chart';element.innerHTML=`<h2>${esc(title)}</h2><canvas></canvas>`;$('#charts').appendChild(element);
  const canvas=element.querySelector('canvas'),ratio=devicePixelRatio||1,width=canvas.clientWidth,height=canvas.clientHeight;canvas.width=width*ratio;canvas.height=height*ratio;canvas.title=series.flatMap(item=>item.x.map((x,index)=>`${item.name}: ${number(x)} / ${number(item.y[index])}`)).join('\\n');
  const ctx=canvas.getContext('2d');ctx.setTransform(ratio,0,0,ratio,0,0);ctx.clearRect(0,0,width,height);
  const margin={left:50,right:10,top:13,bottom:37},plotWidth=width-margin.left-margin.right,plotHeight=height-margin.top-margin.bottom;
  const points=series.flatMap(item=>item.x.map((x,index)=>({x,y:item.y[index]})).filter(point=>Number.isFinite(point.x)&&Number.isFinite(point.y)&&(!options.logX||point.x>0)));
  if(!points.length){ctx.fillStyle='#888';ctx.font='12px sans-serif';ctx.fillText('暂无可比较曲线',margin.left,margin.top+20);return}
  let xMin=Math.min(...points.map(point=>point.x)),xMax=Math.max(...points.map(point=>point.x));
  let yMin=options.yMin??Math.min(...points.map(point=>point.y)),yMax=options.yMax??Math.max(...points.map(point=>point.y));
  if(xMin===xMax)xMax=xMin+1;if(yMin===yMax){yMin-=1;yMax+=1}
  if(options.logX){xMin=Math.log10(Math.max(xMin,1));xMax=Math.log10(Math.max(xMax,10))}
  if(yMin!==options.yMin)yMin-=.06*(yMax-yMin);if(yMax!==options.yMax)yMax+=.06*(yMax-yMin);
  const mapX=value=>margin.left+((options.logX?Math.log10(Math.max(value,1)):value)-xMin)/(xMax-xMin)*plotWidth;
  const mapY=value=>margin.top+plotHeight-(value-yMin)/(yMax-yMin)*plotHeight;
  ctx.font='9px sans-serif';ctx.lineWidth=1;
  for(let index=0;index<=4;index++){const y=margin.top+plotHeight-index*plotHeight/4,value=yMin+(yMax-yMin)*index/4;ctx.strokeStyle='#dedede';ctx.beginPath();ctx.moveTo(margin.left,y);ctx.lineTo(margin.left+plotWidth,y);ctx.stroke();ctx.fillStyle='#555';ctx.textAlign='right';ctx.fillText(number(value,0),margin.left-6,y+3)}
  for(let index=0;index<=4;index++){const x=margin.left+index*plotWidth/4,value=options.logX?Math.pow(10,xMin+(xMax-xMin)*index/4):xMin+(xMax-xMin)*index/4;ctx.strokeStyle='#eee';ctx.beginPath();ctx.moveTo(x,margin.top);ctx.lineTo(x,margin.top+plotHeight);ctx.stroke();ctx.fillStyle='#555';ctx.textAlign=index===0?'left':index===4?'right':'center';ctx.fillText(options.formatX?options.formatX(value):number(value),x,height-7)}
  for(const item of series){ctx.strokeStyle=item.color;ctx.fillStyle=item.color;ctx.lineWidth=1.8;if(item.scatter){item.x.forEach((x,index)=>{if(Number.isFinite(x)&&Number.isFinite(item.y[index])){ctx.beginPath();ctx.arc(mapX(x),mapY(item.y[index]),3.2,0,7);ctx.fill()}});continue}ctx.setLineDash(item.dashed?[5,4]:[]);ctx.beginPath();let started=false;item.x.forEach((x,index)=>{const y=item.y[index];if(!Number.isFinite(x)||!Number.isFinite(y)||options.logX&&x<=0){started=false;return}if(!started){ctx.moveTo(mapX(x),mapY(y));started=true}else ctx.lineTo(mapX(x),mapY(y))});ctx.stroke();ctx.setLineDash([]);if(item.dots)item.x.forEach((x,index)=>{if(Number.isFinite(x)&&Number.isFinite(item.y[index])){ctx.beginPath();ctx.arc(mapX(x),mapY(item.y[index]),2.3,0,7);ctx.fill()}})}
  let legendX=margin.left,legendY=height-22;for(const item of series){if(item.legend===false)continue;if(legendX>width-70){legendX=margin.left;legendY+=11}ctx.strokeStyle=item.color;ctx.setLineDash(item.dashed?[4,3]:[]);ctx.beginPath();ctx.moveTo(legendX,legendY);ctx.lineTo(legendX+12,legendY);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#444';ctx.textAlign='left';ctx.fillText(item.name,legendX+15,legendY+3);legendX+=22+ctx.measureText(item.name).width}
}
function evalSeries(comparison,axis,key){return comparison.map((row,index)=>({name:row.trial.name,x:xValues(row,axis),y:row.evaluation[key]||[],color:curvePalette[index%curvePalette.length],dashed:row.trial.name.startsWith('w4_k200'),dots:key==='mean'&&axis==='env'}))}
function learningSeries(comparison){return comparison.flatMap((row,index)=>{const online=row.online||{},colorValue=curvePalette[index%curvePalette.length],series=[];if(online.mean?.length)series.push({name:`${row.trial.name} online`,x:online.env_steps||[],y:online.mean,color:colorValue,width:2,titleExtra:`eps ${number(row.trial.summary.online_epsilon,3)}`});if(row.evaluation.mean?.length)series.push({name:`${row.trial.name} greedy`,x:row.evaluation.env_steps||[],y:row.evaluation.mean,color:colorValue,dashed:true,width:1.5});if(online.p25?.length)series.push({name:`${row.trial.name} p25`,x:online.env_steps||[],y:online.p25,color:'#999',dashed:true,width:0.8,legend:false});if(online.p75?.length)series.push({name:`${row.trial.name} p75`,x:online.env_steps||[],y:online.p75,color:'#999',dashed:true,width:0.8,legend:false});if(online.p90?.length)series.push({name:`${row.trial.name} p90`,x:online.env_steps||[],y:online.p90,color:'#777',dashed:true,width:0.8,legend:false});return series})}
function drawBars(title,source,value,label){const element=document.createElement('article');element.className='chart';element.innerHTML=`<h2>${esc(title)}</h2><canvas></canvas>`;$('#charts').appendChild(element);const canvas=element.querySelector('canvas'),ratio=devicePixelRatio||1,width=canvas.clientWidth,height=canvas.clientHeight;canvas.width=width*ratio;canvas.height=height*ratio;const ctx=canvas.getContext('2d');ctx.setTransform(ratio,0,0,ratio,0,0);ctx.clearRect(0,0,width,height);const margin={left:42,right:8,top:17,bottom:78},plotWidth=width-margin.left-margin.right,plotHeight=height-margin.top-margin.bottom,values=source.map(row=>value(row)||0),max=Math.max(...values,1);for(let index=0;index<=4;index++){const y=margin.top+plotHeight-index*plotHeight/4;ctx.strokeStyle='#ddd';ctx.beginPath();ctx.moveTo(margin.left,y);ctx.lineTo(margin.left+plotWidth,y);ctx.stroke();ctx.fillStyle='#555';ctx.font='9px sans-serif';ctx.textAlign='right';ctx.fillText(number(max*index/4),margin.left-5,y+3)}const barWidth=Math.max(2,plotWidth/source.length*.74);source.forEach((row,index)=>{const x=margin.left+(index+.5)*plotWidth/source.length,value=values[index],barHeight=value/max*plotHeight;ctx.fillStyle=color(row.trial);ctx.fillRect(x-barWidth/2,margin.top+plotHeight-barHeight,barWidth,barHeight);ctx.save();ctx.translate(x+2,margin.top+plotHeight+4);ctx.rotate(-Math.PI/2);ctx.textAlign='left';ctx.fillStyle='#555';ctx.font='8px sans-serif';ctx.fillText(row.trial.name,0,0);ctx.restore()});ctx.fillStyle='#555';ctx.textAlign='left';ctx.font='9px sans-serif';ctx.fillText(label,margin.left,margin.top+9)}
function renderLedger(visible){$('#body').innerHTML=visible.map(row=>{const trial=row.trial,config=trial.config,summary=trial.summary,evalMeans=row.evaluation.mean||[],best=summary.eval_best??Math.max(0,...evalMeans),shape=config.arch==='mlp'?'mlp':config.arch==='qwen'?'qwen':config.arch==='settf'?'transformer':'',boardLabel=board(trial),onlineSpread=summary.online_last_p25!=null&&summary.online_last_p75!=null?`[${number(summary.online_last_p25)}–${number(summary.online_last_p75)}]`:summary.online_last_p90!=null?`(P90 ${number(summary.online_last_p90)})`:'',onlineScore=summary.online_last==null?'—':`${number(summary.online_last)} ${onlineSpread}`;return `<tr class="${shape} ${boardLabel.includes('200')?'k200':''}"><td><input type="checkbox" data-trial="${esc(trial.id)}" ${selected.has(trial.id)?'checked':''}></td><td title="${esc(trial.id)}">${esc(trial.name)}</td><td>${esc(config.arch||trial.algorithm)}</td><td>${config.params?number(config.params/1e6,2)+'M':'—'}</td><td>${esc(boardLabel)}</td><td>${number(config.batch)}</td><td>${number(summary.grad_steps)}</td><td>${summary.env_steps?number(summary.env_steps/1e6,0)+'M':'—'}</td><td>${number(summary.env_sps)}</td><td>${number((summary.grad_sps||0)*(config.batch||1)/1000,1)}k</td><td title="episodes ${number(summary.online_episodes)}; epsilon ${number(summary.online_epsilon,3)}">${esc(onlineScore)}</td><td>${number(best)}</td><td>${number(summary.eval_last)}</td><td>${number(summary.online_episodes)}</td><td>${number(summary.maxfruit_max)}</td><td>${number(summary.moves_last)}</td><td>${esc(trial.experiment)}</td><td>${esc(config.host)}</td></tr>`}).join('');document.querySelectorAll('[data-trial]').forEach(box=>box.onchange=()=>{if(box.checked)selected.add(box.dataset.trial);else selected.delete(box.dataset.trial);render()})}
function render(){const visible=filtered(),comparison=visible.filter(row=>selected.has(row.trial.id)),onlineCount=comparison.filter(row=>row.online?.mean?.length).length,onlineEpisodes=comparison.reduce((total,row)=>total+(row.trial.summary.online_episodes||0),0);$('#summary').textContent=`${visible.length} trials · ${comparison.length} 条对比曲线 · ${onlineCount} 条含在线 score（${number(onlineEpisodes)} 个 episodes） · 在线 x 轴按 learner 时间戳近似对齐`;$('#ledger-title').textContent=`J. 全部 ${visible.length} 个 trial 台账（橙底 = killy 200；online score 为训练 ε-greedy 回报）`;$('#charts').innerHTML='';if(!visible.length){$('#charts').innerHTML='<div class="empty">没有符合筛选条件的 trial</div>';return}
  drawChart('A. Online episode return vs greedy eval（实线训练 / 同色虚线 greedy）',learningSeries(comparison),{logX:true,formatX:value=>`${number(value/1e6)}M`});drawChart('B. 分数 vs 梯度步数（优化样本效率）',evalSeries(comparison,'grad','mean'),{logX:true});drawChart('C. 分数 vs 墙钟小时',evalSeries(comparison,'hours','mean'),{formatX:value=>`${number(value,1)}h`});
  drawBars('D. 采样吞吐：actor → learner 环境步/秒',[...visible].sort((a,b)=>(b.trial.summary.env_sps||0)-(a.trial.summary.env_sps||0)),row=>row.trial.summary.env_sps,'env/s');drawBars('E. 优化吞吐：每秒训练样本',[...visible].sort((a,b)=>(b.trial.summary.grad_sps||0)*(b.trial.config.batch||1)-(a.trial.summary.grad_sps||0)*(a.trial.config.batch||1)),row=>(row.trial.summary.grad_sps||0)*(row.trial.config.batch||1),'samples/s');
  const compute=[...new Set(visible.map(row=>arch(row.trial)))].map(kind=>{const group=visible.filter(row=>arch(row.trial)===kind);return {name:kind,x:group.map(row=>(row.trial.summary.grad_steps||0)*(row.trial.config.batch||1)),y:group.map(row=>row.trial.summary.eval_best||row.trial.summary.eval_last),color:colors[kind]||colors.other,scatter:true}});drawChart('F. 算力投入 vs 分数上限',compute,{logX:true,formatX:value=>`${number(value/1e9,1)}B`});
  drawChart('G. 最大果型（10 = 西瓜）',evalSeries(comparison,'env','maxfruit_max'),{logX:true,yMin:0,yMax:10,formatX:value=>`${number(value/1e6)}M`});drawChart('H. 单局平均存活步数',evalSeries(comparison,'env','moves_mean'),{logX:true,formatX:value=>`${number(value/1e6)}M`});drawChart('I. P(score ≥ 2000)',evalSeries(comparison,'env','p2000'),{logX:true,yMin:0,yMax:1,formatX:value=>`${number(value/1e6)}M`});renderLedger(visible)}
function fillFilters(){const waves=[...new Set(rows.map(row=>row.trial.experiment).filter(Boolean))].sort(),algorithms=[...new Set(rows.map(row=>arch(row.trial)))].sort();$('#wave').innerHTML='<option value="">全部阶段</option>'+waves.map(wave=>`<option value="${esc(wave)}">${esc(wave)}</option>`).join('');$('#algorithm').innerHTML='<option value="">全部算法</option>'+algorithms.map(item=>`<option value="${esc(item)}">${esc(item)}</option>`).join('');for(const name of preferred){const row=rows.find(item=>item.trial.name===name);if(row)selected.add(row.trial.id)}}
async function refresh(){try{const response=await fetch('/api/rl/overview');rows=await response.json();const wave=$('#wave').value,algorithm=$('#algorithm').value;fillFilters();$('#wave').value=wave;$('#algorithm').value=algorithm;render()}catch(error){$('#summary').textContent='无法载入 trial 数据';console.error(error)}}
$('#wave').onchange=render;$('#algorithm').onchange=render;$('#search').oninput=render;$('#all').onclick=()=>{filtered().forEach(row=>selected.add(row.trial.id));render()};$('#clear').onclick=()=>{selected.clear();render()};refresh();setInterval(refresh,15000);window.addEventListener('resize',render);
</script>
</body></html>"""
